version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow123
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: postgresql://taskflow:taskflow123@postgres:5432/taskflow
      JWT_SECRET: supersecretkey
      REDIS_URL: redis://redis:6379
      MAIL_HOST: smtp.ethereal.email
      MAIL_PORT: 587
      MAIL_USER: david.schroeder@ethereal.email
      MAIL_PASS: yTuE14yjqFF9smJg7M
    depends_on:
      - postgres
      - redis

  worker:
    build: ./backend
    command: node dist/worker.js
    environment:
      DATABASE_URL: postgresql://taskflow:taskflow123@postgres:5432/taskflow
      JWT_SECRET: supersecretkey
      REDIS_URL: redis://redis:6379
      MAIL_HOST: smtp.ethereal.email
      MAIL_PORT: 587
      MAIL_USER: david.schroeder@ethereal.email
      MAIL_PASS: yTuE14yjqFF9smJg7M
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: